sudo: required
dist: trusty
language: c
before_script:
- sudo apt-get install -qq -y --force-yes devscripts groff man-db xmlstarlet texlive-binaries equivs inkscape
- sudo mk-build-deps -i -t "apt-get -qq -y --force-yes --no-install-recommends"
script: "./.travis-build"
notifications:
  on_success: never
  on_failure: change
git:
  depth: 3
addons:
  sonarcloud:
    organization: "flabbergast-config"
    token:
      secure: "z3q7whxV5EBuJvAPYuZDGNwgiqLSXddlvQ7ljQWgThQkVylTfboYpVi0AbCm4sUtMv+OKqI4TWNw+atT4K7j6W0QmP+YKBMmtrPe+pc3RU7BnqZsk9eQkbiUggSsfkZv9fp69X/VGhyFxqk9lCfK1dXVNBNg69R2SIZd69EDkoY="
deploy:
  provider: s3
  access_key_id: AKIAJY7JELRUQJ6ESEWA
  secret_access_key:
    secure: XEIvbH7J10Dq8ZyvOJa6t/WyZ9WShIbbG6jvt9Ak6006pSe9WYKNY3cSDl2omO83LWyr2VS5j3IMA1TI2qRAy130V1NyxL7hlztjjgY6EPtfAstPosgQPkStVWcox+v82KytXMZ87/bWv4sm3cxxLRPHKaAcwZazrgubsKQJaQw=
  bucket: docs.flabbergast.org
  skip_cleanup: true
  local_dir: www
  acl: public_read
