#!/bin/sh

URL="http://docs.flabbergast.org/bootstrap/"
LIMIT=20

set -eu

for HASH in $(git log --pretty=format:%H "HEAD~${LIMIT}..HEAD")
do
	if curl --output /dev/null --silent --head --fail "${URL}/bootstrap-${HASH}.tar.bz2"
	then
		curl -s "${URL}/bootstrap-${HASH}.tar.bz2" | tar xfj -
		echo Bootstrapped to revision $HASH.
		exit 0
	fi
done
echo Could not find a boostrappable revision.
exit 1
