#!/bin/sh

set -eu
for SRC in $(find $(dirname $0)/platform/cli -name '*.cs' -not -name 'compiler-cli.cs' -not -name 'db-cli.cs' -not -name 'Options.cs')
do
	astyle --mode=cs -nqpHU < $SRC | cmp $SRC -
done

for SRC in $(find $(dirname $0)/platform/jvm -name '*.java' -not -name 'compiler-jvm.java' -not -name 'db-jvm.java')
do
	astyle --mode=java --style=java -nqpHU < $SRC | cmp $SRC -
done

