#!/bin/sh

set -eu
test -d $(dirname $0)/tools || mkdir $(dirname $0)/tools

FORMAT_JAR=$(dirname $0)/tools/google-java-format.jar
test -f ${FORMAT_JAR} || wget -O ${FORMAT_JAR} https://github.com/google/google-java-format/releases/download/google-java-format-1.3/google-java-format-1.3-all-deps.jar

astyle --mode=cs -nqpHU $(find $(dirname $0)/platform/cli -name '*.cs' -not -name 'compiler-cli.cs' -not -name 'db-cli.cs' -not -name 'Options.cs' -not -name 'config.cs')
astyle --mode=java --style=java -nqpHU $(find $(dirname $0)/platform/jvm/runtime $(dirname $0)/platform/jvm/compiler $(dirname $0)/platform/jvm/testing -name '*.java' -not -name 'db-jvm.java' -not -name 'Configuration.java')
