#!/bin/sh

set -eu

if [ "x${TRAVIS_TAG:-}" = "x" ]
then
	export TRAVIS_TAG=master
fi

TOPDIR=$(dirname "$0")
TARGET_DIR=${TOPDIR}/www/${TRAVIS_TAG}
TARGET=${TARGET_DIR}/index.xml
HEAD_REV="$(git rev-parse HEAD)"

mkdir -p ${TARGET_DIR}

cat > ${TARGET} <<EOI
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="o_0.xsl" type="text/xsl"?>
<o_0:index xmlns:o_0="http://flabbergast.org/api">
EOI

lexgrog --whatis ${TOPDIR}/*.7 ${TOPDIR}/*.1 ${TOPDIR}/platform/*/*.1 | sed -e 's#^.*/\([a-z_-]*\)\.\([0-9]\): *"[^ ]* - \(.*\)"$#<o_0:man o_0:name="\1" o_0:section="\2" o_0:description="\3" />#' >> ${TARGET}

${TOPDIR}/man2web

. ${TOPDIR}/platform/jvm/testingclasspath.sh
java flabbergast.MainDocumenter -g "https://github.com/flabbergast-config/flabbergast/blob/${HEAD_REV}/stdlib" -o ${TARGET_DIR} ${TOPDIR}/stdlib

for LIB in $(find ${TARGET_DIR} -name 'doc-*.xml')
do
	URI=$(basename $LIB .xml | sed -e 's/^doc-//;s#-#/#g')
	echo "<o_0:ref_link o_0:name=\"${URI}\">" >> ${TARGET}
	xmlstarlet sel -t -m '/o_0:lib[o_0:description]' -c 'o_0:description/*|o_0:description/text()' -t -m '/o_0:lib[not(o_0:description)]' -o "No description available." $LIB >> ${TARGET}
	echo "</o_0:ref_link>" >> ${TARGET}
done
echo '</o_0:index>' >> ${TARGET}

cat > ${TOPDIR}/www/index.xml <<EOI
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="master/o_0.xsl" type="text/xsl"?>
<o_0:versions xmlns="http://www.w3.org/1999/xhtml" xmlns:o_0="http://flabbergast.org/api" o_0:name="Flabergast" o_0:github="https://github.com/flabbergast-config/flabbergast">
<p>Is Flabbergast making you go o_0? If so, start with <a href="https://github.com/flabbergast-config/flabbergast/blob/master/flabbergast-manual.md">the Flabbergast Manual</a>. If you just want to know the name of that template thing that does the stuff, this the right place.</p>
<o_0:version o_0:name="Current" o_0:tag="master"/>
EOI
curl https://api.github.com/repos/flabbergast-config/flabbergast/releases | jq -r '.[] | if .tag_name | tonumber >= 0.19 then "<o_0:version o_0:name=\"\(.name)\" o_0:tag=\"\(.tag_name)\"/>" else empty end' - >> ${TOPDIR}/www/index.xml
echo '</o_0:versions>' >> ${TOPDIR}/www/index.xml

cp -u o_0.css o_0.js o_0.xsl o_0-xref.xsl o_0-index.css o_0-index.xsl ${TARGET_DIR}
cp -u o_0.css o_0-index.css o_0-versions.xsl ${TOPDIR}/www

inkscape -e ${TOPDIR}/www/nuget-icon.png -w 64 -h 64 flabbergast.svg
for size in 16 32 64
do
	inkscape -e ${TOPDIR}/www/icon${size}.png -w ${size} -h ${size} flabbergast.svg
done
