#!/bin/sh
set -e
case "$1" in
	remove|purge)
		find /usr/share/flabbergast/lib -name '*.dll' -exec rm {} \;
		test ! -d /usr/local/share/flabbergast/lib || find /usr/share/flabbergast/lib -name '*.dll' -exec rm {} \;
		update-flabbergast
		;;
		upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
	*)
		echo "postrm called with unknown argument '$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
