.\" Authors: Andre Masella
.TH flabbergast 1 "April 2015" "0.0" "USER COMMANDS"
.SH NAME 
nflabbergast \- Render a Flabbergast file using the Common Language Infrastructure
.SH SYNOPSIS
.B nflabbergast
.I input.o_0
[
.B \-o
.I output.txt
] [
.B \-p
] [
.B \-t
]
.SH DESCRIPTION
Runs the Flabbergast interpreter on the provided file and writes the \fBvalue\fR attribute to standard output, or a specified file.

.SH OPTIONS
.TP
\-o
A file to overwrite with the output instead of writing to standard output.
.TP
\-p
Do not load pre-compiled libraries. Only use source libraries, compiled as needed. Use this if the cache is out-of-date or \fBFLABBERGAST_PATH\fR has libraries that shadow ones provided in the distribution.
.TP
\-t
Print the traversal of the parser. This is a lot of useless information.
.SH ENVIRONMENT VARIABLES
.TP
FLABBERGAST_PATH
A list of directories to search for included libraries (\fBFrom lib:\fR). If precompiled libraries are found, they are used. If not, the libraries are dynamically compiled. These can be refereshed using
.BR update-flabbergast (1).
When searching for libraries, files names ending in both \fB.o_0\fR and \fB.no_0\fR are used, where the latter is for platform-specific libraries
.SH SEE ALSO
.BR flabbergast_language (7),
.BR jflabbergast (1),
.BR nflabbergast-repl (1).
