#!/bin/sh

set -eux

for i in 1 2 15
do
	trap 'rm -rf .build; trap - '$i'; kill -s '$i' $$' $i
done
trap 'EC=$?; rm -rf .build; exit $EC' EXIT

PKG="$1"
VER="$2"
PREFIX="flabbergast-${PKG}-${VER}"
shift 2
test -d "$PKG"
rm -rf .build

SOURCEPATH="$PKG"
for each in "$@"
do
	SOURCEPATH="$SOURCEPATH:$each"
done

# Source JAR
${JAR-jar} cfm "${PREFIX}-sources.jar" "${PKG}.manifest" -C "$PKG" .
for each in "$@"
do
	${JAR-jar} uf "${PREFIX}-sources.jar" -C "$each" .
done

# JavaDoc JAR
mkdir .build
${JAVADOC-javadoc} -quiet -encoding UTF-8 -sourcepath "$SOURCEPATH" -d .build $(find "$PKG" "$@" -name '*.java')
${JAR-jar} cfm "${PREFIX}-javadoc.jar" "${PKG}.manifest" -C .build .
rm -rf .build

# Binary JAR
mkdir .build
${JAVAC-javac} -source 1.8 -target 1.8 -g -encoding UTF-8 -sourcepath "$SOURCEPATH" -d .build $(find "$PKG" "$@" -name '*.java')
${JAR-jar} cfm "${PREFIX}.jar" "${PKG}.manifest" -C .build .
rm -rf .build
