.\" Authors: Andre Masella
.TH flabbergast 1 "April 2015" "0.0" "USER COMMANDS"
.SH NAME 
jflabbergast \- Render a Flabbergast file using the Java Virtual Machine
.SH SYNOPSIS
.B jflabbergast
.I input.o_0
[
.B \-o
.I output.txt
] [
.B \-p
] [
.B \-t
]
.SH DESCRIPTION
Runs the Flabbergast interpreter on the provided file and writes the \fBvalue\fR attribute to standard output, or a specified file.

.SH OPTIONS
.TP
\-o
A file to overwrite with the output instead of writing to standard output.
.TP
\-p
Do not load pre-compiled libraries. Only use source libraries, compiled as needed. Use this if the cache is out-of-date or \fBFLABBERGAST_PATH\fR has libraries that shadow ones provided in the distribution.
.TP
\-t
Print the traversal of the parser. This is a lot of useless information.
.SH ENVIRONMENT VARIABLES
.TP
FLABBERGAST_PATH
A list of directories to search for included libraries (\fBFrom lib:\fR). If precompiled libraries are found, they are used. If not, the libraries are dynamically compiled. These can be refereshed using
.BR update-flabbergast (1).

.SH URI SCHEMES
The currently supported schemes are listed below.

.TP
\fBcurrent:\fRvariable
Information about the executing Flabbergast instance.
.RS
.TP
\fBcurrent:directory\fR
The working directory of the executing Flabbergast instance.

.TP
\fBcurrent:interactive\fR
True if the executing Flabbergast instance is executing interactive (REPL), false if in batch mode.

.TP
\fBcurrent:login\fR
The OS-specific login name of the user executing Flabbergast.

.TP
\fBcurrent:version\fR
The Flabbergast version, as a float.

.TP
\fBcurrent:vm/name\fR
The virtual machine Flabbergast is executing on. Currently, either \fBCLR\fR or \fBJVM\fR.

.TP
\fBcurrent:vm/vendor\fR
The creator of virtual machine Flabbergast is executing on.

.TP
\fBcurrent:vm/version\fR
The version of virtual machine Flabbergast is executing on (as a string).
.RE

.TP
\fBenv:\fRvariable
Access UNIX environment variables. The variable name must consist of uppercase letters, numbers, and underscore, and must not begin with a number, per the IEEE Std 1003.1 section 8.1. If an environment variable is defined, it will be returned as a string. If the variable is undefined, \fBNull\fR will be returned instead.

It's important to note that, by design, there is no way to inspect the entire environment or lookup an environment variable using a string.

.TP
\fBfile://\fRpath
Read the contents of a file and return the a \fBBin\fR containing the results.

.TP
\fBftp\fR[\fBs\fR]\fB://\fRhost\fB/\fRpath
Download a file over FTP and return a \fBBin\fR containing the results.

.TP
\fBhttp\fR[\fBs\fR]\fB://\fRhost\fB/\fRpath
Download a file over HTTP. The result is a frame with the following attributes:
.RS
.TP
data
A \fBBin\fR containing the downloaded data.

.TP
content_type
The value of the HTTP \fBContent-Type\fR header.
.RE

.TP
\fBlib:\fRpath
This imports a Flabbergast library. Libraries are regular Flabbergast files that do not need to have a \fBvalue\fR attribute. The allow names of Flabbergast libraries are intentionally limited to ASCII letters and digits, separated by \fB/\fR. Note this excludes underscore. When a library is referenced, it can be loaded from three places: a pre-compilation cache, a source file, or a fixed pre-compiled library. These places are checked in order. The pre-compiled cache can be disabled on the command-line with \fB-p\fR to
.BR jflabbergast (1)
and
.BR nflabbergast (1).

The pre-compilation caches and sources are checked in the same way. Each location is checked for a matching file ending in either \fB.o_0\fR or a platform-specific \fB.jo_0\fR on the JVM and \fB.no_0\fR on the CLR. No verification is done to determine if the pre-compiled cache is up-to-date. Therefore, it is important to update the cache using
.BR update-flabbergast (1).
The following locations are checked, in order:

.RS
.IP 1.
A directory named \fBlib\fR in the same directory as the input Flabbergast file. In the case of the REPL, if no input file is provided, the current directory is used.
.IP 2.
Any directories listed in the environment variable \fBFLABBERGAST_PATH\fR, listed in order.
.IP 3.
The directory \fB$HOME/.local/share/flabbergast/lib\fR on UNIX or \fB%localappdata%/flabbergast/lib\fR on Windows.
.IP 4.
The directory \fB$PREFIX/share/flabbergast/lib\fR, where \fB$PREFIX\fR was supplied at compile time.
.IP 5.
The directory \fB/usr/share/flabbergast/lib\fR.
.IP 6.
The directory \fB/usr/local/share/flabbergast/lib\fR.
.RE

The JVM edition of Flabbergast JAR ships with a precompiled version of the libraries distributed with Flabbergast. These are chosen as a final fallback.

.TP
\fBres:\fRpath
Reads a file and returns the contents as a \fBBin\fR. The same set of directories as for \fBlib\fR is searched. This is meant for resource files.

.TP
\fBsetting:\fRkey
Reads an application setting and returns the matching string or, if the key is missing, \fBNull\fR. This is equivalent to calling \fBjava.lang.System.getProperty("\fIkey\fB")\fR method.

.TP
\fBsql+\fRprovider\fB:\fRpath
Opens a database connection for databases that stores data as a local file.

.TP
\fBsql+\fRprovider\fB://\fR[user[\fB:\fRpassword]\fB@\fR]host[\fB:\fRport]\fB/\fRcatalog
Connects to a database server to a server. The remote \fIuser\fR and \fIpassword\fR maybe specified, if needed. The remote \fIhost\fR must be supplied with an optional \fIport\fR. Finally, the \fIcatalog\fR or database must be provided.

.TP
\fBsql+\fRprovider\fB:\fRname
Connects to a database using a vendor-specific name.

.SH SUPPORTED DATABASES (PROVIDERS)
The appropriate driver JAR must be added to the \fBCLASSPATH\fR or place in \fB$PREFIX/share/flabbergast/jvm\fR. Parameters maybe given in URL standard \fB?\fIkey\fB=\fIvalue\fB&\fIkey\fB=\fIvalue\fR style for any database URI. The allow parameters are described for each database.

.SS Microsoft SQL Server (mssql)
This database uses the \fBsql+mssql\fR\fB://\fR[user[\fB:\fRpassword]\fB@\fR]host[\fB:\fRport]\fB/\fRcatalog URI format.

No parameters are supported.

.SS mySQL (mysql)
This database uses the \fBsql+mysql\fR\fB://\fR[user[\fB:\fRpassword]\fB@\fR]host[\fB:\fRport]\fB/\fRcatalog URI format.

No parameters are supported.

.SS Oracle via Host (oracle+host)
This database uses the \fBsql+oracle+host\fR\fB://\fR[user[\fB:\fRpassword]\fB@\fR]host[\fB:\fRport]\fB/\fRcatalog URI format.

No parameters are supported.

.SS Oracle via TNS (oracle+tns)
This database uses the \fBsql+oracle+tns\fR\fB:\fRtnsname URI format.

No parameters are supported.

.SS PostgreSQL (postgresql)
This database uses the \fBsql+postgresql\fR\fB://\fR[user[\fB:\fRpassword]\fB@\fR]host[\fB:\fRport]\fB/\fRcatalog URI format.

.TP
ssl
Requires SSL encryption with server. May be \fBtrue\fR or \fBfalse\fR.

.SS SQLite (sqlite)
This database uses the \fBsql+sqlite\fR\fB:\fRpath URI format.

No parameters are supported.

.SS SQLite via Resource (sqlite+res)
This database uses the \fBsql+sqlite+res\fR\fB:\fRfile URI format.

No parameters are supported.

The specified file will be searched in locations where the \fBres:\fR URI will search with the possible extensions:
.IP \(bu 4
.B .sqlite
.IP \(bu 4
.B .sqlite3
.IP \(bu 4
.B .db
.IP \(bu 4
.B .db3
.IP \(bu 4
.B .s3db


.SH SEE ALSO
.BR flabbergast_language (7),
.BR jflabbergast-repl (1).
