.\" Authors: Andre Masella
.TH flabbergast 1 "April 2015" "0.0" "USER COMMANDS"
.SH NAME 
jflabbergast \- Render a Flabbergast file using the Java Virtual Machine
.SH SYNOPSIS
.B jflabbergast
.I input.flbgst
[
.B \-o
.I output.txt
] [
.B \-t 
]
.SH DESCRIPTION
Runs the Flabbergast interpreter on the provided file and writes the \fBvalue\fR attribute to standard output, or a specified file.

.SH OPTIONS
.TP
\-o
A file to overwrite with the output instead of writing to standard output.
.TP
\-t
Print the traversal of the parser. This is a lot of useless information.
.SH ENVIRONMENT VARIABLES
.TP
FLABBERGAST_PATH
A list of directories to search for included libraries (\fBFrom lib:\fR). If precompiled libraries are found, they are used. If not, the libraries are dynamically compiled. These can be refereshed using
.BR update-flabbergast (1).
.SH SPECIAL SYNTAX
This version of Flabbergast has special syntax for interoperating with other programs.

.TP
\fBXInvoke\fR \fItype method\fB(\fIexpr\fB, \fR...\fB)\fR
Calls a static or virtual method for a type using the supplied expressions as parameters. If the method is an instance method, the first argument must be the instance to use. The method cannot return \fBvoid\fR and cannot throw an exception. The return value of the method must be convertible to a Flabbergast type. Overload resolution is done automatically.


.SH SEE ALSO
.BR flabbergast_language (7),
.BR nflabbergast (1),
.BR jflabbergast-repl (1).
